#!/usr/bin/env julia

using Dates
using TOML

const ROOT = normpath(joinpath(@__DIR__, ".."))
const CONFIG_PATH = joinpath(ROOT, "data", "dashboard.toml")
const RECORDS_PATH = joinpath(ROOT, "data", "records.csv")
const OUTPUT_PATH = joinpath(ROOT, "docs", "data.js")

const REQUIRED_COLUMNS = [
    "date",
    "commit",
    "branch",
    "julia",
    "rxinfer",
    "benchmark",
    "scenario",
    "metric",
    "value",
]

function parse_csv_line(line::AbstractString)
    fields = String[]
    buffer = IOBuffer()
    in_quotes = false
    i = firstindex(line)

    while i <= lastindex(line)
        char = line[i]
        if in_quotes
            if char == '"'
                next_i = nextind(line, i)
                if next_i <= lastindex(line) && line[next_i] == '"'
                    write(buffer, '"')
                    i = nextind(line, next_i)
                else
                    in_quotes = false
                    i = next_i
                end
            else
                write(buffer, char)
                i = nextind(line, i)
            end
        else
            if char == '"'
                in_quotes = true
                i = nextind(line, i)
            elseif char == ','
                push!(fields, String(take!(buffer)))
                i = nextind(line, i)
            else
                write(buffer, char)
                i = nextind(line, i)
            end
        end
    end

    in_quotes && error("Unclosed quote in CSV line: $(line)")
    push!(fields, String(take!(buffer)))
    return fields
end

function read_records(path)
    lines = filter(!isempty, strip.(readlines(path)))
    isempty(lines) && error("No records found in $(path)")

    header = parse_csv_line(first(lines))
    header == REQUIRED_COLUMNS || error(
        "Unexpected CSV header in $(path).\nExpected: $(join(REQUIRED_COLUMNS, ", "))\nFound: $(join(header, ", "))",
    )

    records = Vector{Vector{Any}}()
    for (line_number, line) in enumerate(lines[2:end])
        fields = parse_csv_line(line)
        length(fields) == length(REQUIRED_COLUMNS) || error(
            "Line $(line_number + 1) in $(path) has $(length(fields)) fields, expected $(length(REQUIRED_COLUMNS))",
        )

        value = tryparse(Float64, fields[end])
        isnothing(value) && error("Line $(line_number + 1) has a non-numeric value: $(fields[end])")
        push!(records, Any[fields[1:end-1]..., value])
    end

    return records
end

js_escape(value) = replace(
    string(value),
    "\\" => "\\\\",
    "\"" => "\\\"",
    "\n" => "\\n",
    "\r" => "\\r",
    "\t" => "\\t",
)
js_string(value) = "\"" * js_escape(value) * "\""
js_bool(value::Bool) = value ? "true" : "false"

function js_value(value)
    if value isa Bool
        return js_bool(value)
    elseif value isa Real
        return string(value)
    elseif value isa AbstractVector
        return "[" * join(js_value.(value), ", ") * "]"
    else
        return js_string(value)
    end
end

function validate!(config, records)
    metrics = get(config, "metrics", [])
    benchmarks = get(config, "benchmarks", [])

    isempty(metrics) && error("No [[metrics]] entries found in $(CONFIG_PATH)")
    isempty(benchmarks) && error("No [[benchmarks]] entries found in $(CONFIG_PATH)")

    metric_ids = Set(metric["id"] for metric in metrics)
    benchmark_ids = Set(benchmark["id"] for benchmark in benchmarks)

    for (index, record) in enumerate(records)
        benchmark = record[6]
        metric = record[8]
        benchmark in benchmark_ids || error("Record $(index) references unknown benchmark id: $(benchmark)")
        metric in metric_ids || error("Record $(index) references unknown metric id: $(metric)")
    end
end

function write_data_js(io, config, records)
    generated_at = Dates.format(now(UTC), dateformat"yyyy-mm-ddTHH:MM:SSZ")
    metrics = config["metrics"]
    benchmarks = config["benchmarks"]

    println(io, "// This file is generated by scripts/generate_dashboard_data.jl.")
    println(io, "// Edit data/dashboard.toml and data/records.csv, then run `make dashboard`.")
    println(io, "window.RXINFER_DASHBOARD_DATA = {")
    println(io, "  generatedAt: $(js_string(generated_at)),")
    println(io)

    println(io, "  metrics: [")
    for (index, metric) in enumerate(metrics)
        comma = index == length(metrics) ? "" : ","
        println(
            io,
            "    { id: $(js_string(metric["id"])), label: $(js_string(metric["label"])), unit: $(js_string(metric["unit"])), lowerIsBetter: $(js_bool(metric["lower_is_better"])) }$(comma)",
        )
    end
    println(io, "  ],")
    println(io)

    println(io, "  benchmarks: [")
    for (index, benchmark) in enumerate(benchmarks)
        comma = index == length(benchmarks) ? "" : ","
        tags = get(benchmark, "tags", String[])
        println(io, "    {")
        println(io, "      id: $(js_string(benchmark["id"])),")
        println(io, "      category: $(js_string(benchmark["category"])),")
        println(io, "      title: $(js_string(benchmark["title"])),")
        println(io, "      description: $(js_string(benchmark["description"])),")
        println(io, "      tags: $(js_value(tags))")
        println(io, "    }$(comma)")
    end
    println(io, "  ],")
    println(io)

    println(io, "  // Columns:")
    println(io, "  // $(join(REQUIRED_COLUMNS, ", "))")
    println(io, "  records: [")
    for (index, record) in enumerate(records)
        comma = index == length(records) ? "" : ","
        println(io, "    $(js_value(record))$(comma)")
    end
    println(io, "  ]")
    println(io, "};")
end

function main()
    isfile(CONFIG_PATH) || error("Missing $(CONFIG_PATH)")
    isfile(RECORDS_PATH) || error("Missing $(RECORDS_PATH)")

    config = TOML.parsefile(CONFIG_PATH)
    records = read_records(RECORDS_PATH)
    validate!(config, records)

    mkpath(dirname(OUTPUT_PATH))
    open(OUTPUT_PATH, "w") do io
        write_data_js(io, config, records)
    end

    println("Generated $(relpath(OUTPUT_PATH, ROOT)) from $(length(records)) records.")
end

main()
